train_file: "train.csv"
dev_file: "dev.csv"
test_file: "test.csv"
hypersearch: true
params:
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 2
  warmup_steps: 500
  weight_decay: 0.01