train_file: train.csv
test_file: test.csv
dev_file: dev.csv
params:
  gradient_accumulation_steps: 2
  learning_rate: 0.001953539839844359
  num_train_epochs: 2
  per_device_train_batch_size: 32
  seed: 9
